### PR TITLE
-…

### PR DESCRIPTION
**Pull request by ahandleman**
Added a times helper for Handlebars to reduce repeated code in actor-features

Updated actor-features to use this.

Added increment XP and set XP to automatically reset when at max.

Unsure if you want this merged - I'm planning on adding a modal so that when you click the XP button, it will ask you the relevant post-session questions and update accordingly.  That won't be tonight though - still familiarizing with Handlebars/Foundry

### CODE REVIEW

**Comment by diabeatz96** [comment]
Your changes are great, I think this makes the experience of adding XP improved. I have gone ahaead and added in more css styling to improve aesthetics of what you've done.

**Please update the system.JSON to v1.0.19, and change actor features to this code and it is solid. Feel free to adjust my CSS to be more fitting / something you prefer more.** 
image

```hbs
<style>
  .roller-box {
    background-color: #2c2c2c;
    border: 2px solid red;
    padding: 10px;
    border-radius: 5px;
    margin-bottom: 20px;
  }
  .roller-box .resource-label {
    color: white;
  }
  .roller-box .flex-group-center {
    display: flex;
    flex-direction: column;
    align-items: flex-start;
  }
  .roller-box .checkbox-group {
    display: flex;
    justify-content: space-between;
    width: 100%;
  }
  .roller-box .checkbox-group .resource {
    margin-right: 10px;
  }
  .roller-box .demon-checkbox {
    display: flex;
    align-items: center;
    justify-content: center;
    margin-bottom: 10px;
  }
  .roller-box .demon-checkbox input[type="checkbox"] {
    margin-right: 5px;
  }
  .roller-box .demon-checkbox label {
    color: red;
    font-weight: bold;
  }
  .xp-button {
    background-color: red;
  }
  .roller-box select {
    border: 1px solid red;
    background-color: white;
  }
  .roller-box .roll-button {
    display: flex;
    justify-content: center;
    margin-top: 10px;
    width: 100%;
  }
  .roller-box .roll-button button {
    background-color: red;
    color: white;
    border: none;
    padding: 10px 20px;
    cursor: pointer;
    border-radius: 5px;
  }
  .resource-header {
    color: white;
  }
  .flex-group {
    display: flex;
    align-items: center;
  }
  .flex-group .resource,
  .flex-group .demon-checkbox {
    margin-right: 10px;
  }
  .advancements-experience-box {
    background-color: #2c2c2c;
    border: 2px solid red;
    padding: 10px;
    border-radius: 5px;
    margin-top: 20px;
    margin-bottom: 20px;
    color: white;
  }
  .advancements-experience-box .resource-label {
    color: white;
  }
  .advancements-experience-box .checkbox-group {
    display: flex;
    justify-content: space-between;
    width: 100%;
  }
  .advancements-experience-box .checkbox-group .resource {
    margin-right: 10px;
  }
  .advancements-experience-box .xp-button {
    background-color: red;
  }
</style>

<h3 class='resource-header'>Cat Level</h3>
<div class="resource">
  <div class="checkbox-group checkbox-group_cat" data-field="CATLEVEL">
    {{#times 7}}
    <div class="checkbox-item checkbox-item_cat">
      <img src="systems/cain/assets/CAT/CAT{{@index}}.png" alt="CAT {{@index}}">
      <label for="CATLEVEL-{{@index}}">Level {{@index}}</label>
      <input type="checkbox" name="CATLEVEL-{{@index}}" {{#if (gte system.CATLEVEL.value @index)}}checked{{/if}}/>
    </div>
    {{/times}}
  </div>
</div>

  <div class="advancements-experience-box">
    <div class="resource" style="font-family: 'Courier New', Courier, monospace;">
      <label for="xp"> <h2 class="resource-header">XP & Advancements</h3></label> 
      <output id="xp-output" style="display: block; font-size: 1.2em;">{{system.xp.value}} / {{system.xp.max}}</output>   
      <button id="increment-xp-value" class="xp-button" style="background-color: #660000; color: white; padding: 10px 20px; border: none; border-radius: 5px; cursor: pointer; font-size: 1em;">
        Gain XP
      </button>
      <div class="checkbox-group" data-field="xp" style="margin-top: 10px;">
        {{#times system.xp.max}}
        <input type="checkbox" id="xp-checkbox-{{@index}}" name="xp-{{@index}}" {{#if (gte system.xp.value @index)}}checked{{/if}} disabled/>
        {{/times}}
      </div>
    </div>

    <div class="resource">
      <label for="system.advancements.value" class="resource-label">Advancements</label>
      <output id="advancements-output">{{system.advancements.value}}</output>
      <div class="resource-content flexrow flex-center">
        <input type="range" name="system.advancements.value" value="{{system.advancements.value}}" min="0" max="4" step="1" data-dtype="Number" oninput="document.getElementById('advancements-output').value = this.value">
      </div>
    </div>
  </div>

<div class="grid grid-3col">
  <div class="resource">
    <label for="divineAgony">Divine Agony</label>
    <div class="checkbox-group" data-field="divineAgony">
      {{#times 3}}
      <input type="checkbox" name="divineAgony-{{@index}}" {{#if (gte system.divineAgony.value @index)}}checked{{/if}}/>
      {{/times}}
    </div>
  </div>

  <div class="resource">
    <label for="injuries">Injuries</label>
    <div class="checkbox-group" data-field="injuries">
      {{#times 3}}
      <input type="checkbox" name="injuries-{{@index}}" {{#if (gte system.injuries.value @index)}}checked{{/if}}/>
      {{/times}}
    </div>
  </div>

  <div class="resource">
    <label for="stress">Stress</label>
    <div class="checkbox-group" data-field="stress">
      {{#times 6}}
      <input type="checkbox" name="stress-{{@index}}" {{#if (gte system.stress.value @index)}}checked{{/if}}/>
      {{/times}}
    </div>
  </div>
</div>

<div class="roller-box">
  <h2 class="resource-header">Dice Roller</h2>
  <div class="flex-group-center">
    <div class="flex-group">
      <div class="resource">
        <label for="system.skill" class="resource-label">Select Skill</label>
        <select name="system.skill" data-dtype="String">
          {{#each @root.config.skills as |skill key|}}
            <option value="{{key}}" {{#if (eq system.skill key)}}selected{{/if}}>{{localize skill}}</option>
          {{/each}}
        </select>
      </div>
      <div class="demon-checkbox">
        <input id="use-divine-agony" type="checkbox" name="use-divine-agony" value="0">
        <label for="use-divine-agony">Use Divine Agony</label>
      </div>
    </div>
    <div class="checkbox-group">
      <div class="resource">
        <label for="teamwork">Teamwork</label>
        <input id="teamwork" type="checkbox" name="teamwork" value="0">
      </div>
      <div class="resource">
        <label for="setupPage">Setup</label>
        <input id="setupPage" type="checkbox" name="setup" value="0">
      </div>
      <div class="resource">
        <label for="hard">Hard</label>
        <input id="hard" type="checkbox" name="hard" value="0">
      </div>
      <div class="resource">
        <label for="extra-dice">Extra Dice</label>
        <input id="extra-dice" type="number" name="extra-dice" value="0" min="0">
      </div>
    </div>
    <div class="roll-button">
      <button type="button">Roll</button>
    </div>
  </div>
</div>

<h2>ADVANCEMENT</h2>
<p>At the end of each session, answer each question, then mark xp. Cash an advance each time you mark 4.</p>
<ul>
  <li>Did you survive?</li>
  <li>Did you follow your first agenda item?</li>
  <li>Did you follow at least one bolded agenda item?</li>
  <li>Did you follow two or more bolded agenda items?</li>
  <li>Did you take an injury or affliction?</li>
</ul>

<h2>ACTION ASSESSMENT METRIC</h2>
<div class="grid grid-3col flex-group-center">
  <p>4+<br>SUCCESS</p>
  <p>RISKY<br>Admin rolls the risk die</p>
  <p>HARD<br>Successes on a 6</p>
</div>

<ul>
  <li>Teamwork (Combine highest bonuses)</li>
  <li>Setup yourself or another: (+1D, -risk, or -hard)</li>
  <li>Spend 1 psyche burst to use your powers (+1D)</li>
  <li>Use your abilities</li>
  <li>Bargain with the Admin (Gain a hook or tradeoff)</li>
  <li>… +3 dice maximum</li>
</ul>
```

**Comment by diabeatz96** [comment]
Actually, please make your version 1.0.20 in your system.json file. Thank you. I need to adjust logic in my workflow later to auto adjust system updating for release.

**Comment by ahandleman** [comment]
Should be good now

**Comment by ahandleman** [comment]
I also merged in the fix for #16 to this PR.  It's a very small code change
image

**Review by diabeatz96 — APPROVED** [review]

**Pull request merged**
