### PR TITLE
Created system to bring up form when ending session

### PR DESCRIPTION
**Pull request by ahandleman**
I added a form that is brought up when gaining XP that will ask the player about each of their agendas and automatically calculate XP.  

This PR is not ready to be merged, it will need an updated json and css for the form.

### CODE REVIEW

**Comment by ahandleman** [comment]
Also - I want to take a second look at how I'm doing the XP logic.  I think it might be a good idea to move some of that around to better consolidate the logic for future changes.

**Comment by ahandleman** [comment]
Other things to consider about this PR
 - Currently the system does not enforce the invariant that you can only have one unbolded agenda.  This is an invariant in the game, so it might be worth looking into.  That would require a revamp of how we manage bolded vs unbolded agenda items.  The current version of the PR allows for multiple unbolded agendas, and simply restricts you to a max of 1 xp from unbolded agendas.

**Comment by ahandleman** [comment]
PR just about ready - need to update system.json.

Would it be helpful to have a dev branch to consolidate changes to prevent releasing a new version for every change?  Then merge the dev branch once a day

**Comment by diabeatz96** [comment]
I will create  dev off of main now to hold our changes there and then update when we see fit to push new release item

**Comment by diabeatz96** [comment]
Please use development now for PRs and changes and then we will update and push development branch into main when necessary,

**Comment by diabeatz96** [comment]
Enjoying the changes, few minor notes and changes. 

1. To keep the system free form, i think we should keep users to input any amount of unbolded agendas they want and any amount of bolded agendas they want. There is a world I can see where we implement boldedAgendasItems and unBoldedAgendaItems as two seperate schema items, but I think its okay to have the user add as many unbolded / bolded as they want. Someone could in theory homebrew an agenda that lets you take two unbolded items or you can have "two unbolded" at the same time.  (So i would not cap at 1, just let them click check for bolded / unbolded). 

2.)  perhaps we change label to be here of current / max to be here? 
image

3.) If they have forgotten to fill out an agenda or havent added it in yet, perhaps we can add a message if no bold agendas or normal agendas "Please go to your abilities tab and add agenda items there..." 

image)

**Pull request closed without merging**
